name: CI workflow
on:
  push:
  pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Check if dependencies cached before run
            - name: List cached directories before dependency installation
              run: ls ~/.cache/pip || true

            # Cache dependencies
            - name: Set up cache
              uses: actions/cache@v3
              with:
                path: |
                  %APPDATA%\pip\Cache  # This is the path where pip stores dependencies
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            #- name: Linting with Flake8
            #  run: |
            #        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
            #        flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
            #- name: Testing coverage with Nodetests
            #  run: |
            #        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

                    
            # Check if dependencies cached after run
            - name: List cached directories after dependency installation
              run: ls ~/.cache/pip || true



