name: CI workflow
on:
  push:
  pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        env:
          PIP_CACHE_DIR: /cache/pip  # Set custom cache directory
    
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Cache dependencies
            - name: Set up Dependencies Cache
              uses: actions/cache@v3
              with:
                path: /cache/pip
                key: Linux-pip-5a10801b288f9708023ca35be6b49ba1ed92ff245458982f0b7795057b587f54
                restore-keys: Linux-pip-24.0-

            # Check if cache hit occurred
            - name: Check if cache hit
              id: cache-check
              run: echo "::set-output name=cache-hit::$(echo ${{ steps.cache-check.outputs.cache-hit }})"
      
            # Install dependencies only if cache was not hit
            - name: Install dependencies
              if: steps.cache-check.outputs.cache-hit != 'true'
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

                
            - name: Linting with Flake8
              run: |
                    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                    flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
            - name: Testing coverage with Nodetests
              run: |
                    nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

                    
            # Check if dependencies cached after run
            - name: List cached directories after dependency installation
              run: ls /cache/pip || true



